#
# Makefile - Lattic FPGA Linux driver.
# Copyright(c) 2018, Quanta Corporation.
#
obj-$(CONFIG_FPGA_LIFMD6000)	+= fpga_lifmd6000.o
fpga_lifmd6000-objs := lifmd6000.o
fpga_lifmd6000-objs += fpga_data.o

